### ISSUE TITLE
Crashes editor

### ISSUE THREAD

**Issue by wabudd1** [luke-john/print-atom#2]
Prints "correctly", but immediately crashes the editor.  I don't think this is quite ready for the limelight, but it's a good start.

**Comment by luke-john** [comment]
Hey @wabudd1, sorry about that. 

I've not been using atom for some time now and am unlikely to investigate and fix this.

I've added a note to the plugins description so hopefully no one else will burn time with this.

sorry.

**Comment by wabudd1** [comment]
@luke-john About as much as I can expect from a solo project.  Thanks for making it!
